---
title: "prepare-data (experimental)"
author: "Daniel Moul"
date: "`r Sys.Date()`"
output: html_document
---

<br><br>

***This is an experimental script used prior to the development of nc-camping-writeup.Rmd. It is not needed and may not work correctly.***

<br>

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = FALSE)
# 
# library(tidyverse, warn.conflicts = FALSE)
# library(arrow, warn.conflicts = FALSE)
# library(jsonlite)
# library(janitor)
# library(gt)
# library(scales)
# library(glue)
# library(lubridate)
# library(purrr)
# 
# library(hrbrthemes)
# # remotes::install_github("hrbrmstr/hrbrthemes")
# # run 2021-08-01 to address segfault errors like this:
# # sh: line 1: 11020 Segmentation fault: 11  '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rttf2pt1/exec//ttf2pt1' -a -GfAe '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/hrbrthemes/fonts/roboto-condensed/RobotoCondensed-Bold.ttf' '/var/folders/0j/hjw8sflx19l6rw4s1l68qq640000gn/T//RtmpGN3PSJ/fonts/RobotoCondensed-Bold' 2>&1
# theme_set(theme_ipsum_ps() + 
#             theme(panel.grid.minor = element_blank()))
# import_plex_sans()
# 
# # library(readr)
# # options(readr.read_lazy = TRUE)
# 
# options(dplyr.summarise.inform = FALSE)
# 
# big_campground_size <- 50 # fifty or more campsites

```

```{r}
# #facilities (facilityID and parentorgid)
# facilities_raw <- fromJSON("./data/raw/RIDBFullExport_V1_JSON/Facilities_API_v1.json",
#                       flatten = FALSE)
# facilities <- facilities_raw[[1]] %>%
#   clean_names() %>%
#   rename(geometry = geojson) %>%
#   select(-c(legacy_facility_id, 
#             facility_description, # would like to keep but this is a big field)
#             facility_use_fee_description, # has come info about camping (individual / group) that might be helpful
#             facility_directions:facility_ada_access,
#             stay_limit,
#             enabled)
#   ) %>%
#   mutate(keywords = str_to_lower(keywords))

#rec_areas <- read_json_arrow("./data/raw/RIDBFullExport_V1_JSON/RecAreas_API_v1.json")
# rec_areas_raw <- fromJSON("./data/raw/RIDBFullExport_V1_JSON/RecAreas_API_v1.json",
#                       flatten = FALSE)
# rec_areas <- rec_areas_raw[[1]] %>%
#   clean_names()

# campsites (campsidetid and facilityid)
# campsites_raw <- fromJSON("./data/raw/RIDBFullExport_V1_JSON/Campsites_API_v1.json",
#                       flatten = FALSE)
# campsites <- campsites_raw[[1]] %>%
#   clean_names()

# attributes per campsite (entityid) - this is too much detail
# campsite_attributes_raw <- fromJSON("./data/raw/RIDBFullExport_V1_JSON/CampsiteAttributes_API_v1.json",
#                       flatten = FALSE)
# campsite_attributes <- campsite_attributes_raw[[1]] %>%
#   clean_names()

# activityid codes
# activities_raw <- fromJSON("./data/raw/RIDBFullExport_V1_JSON/Activities_API_v1.json",
#                       flatten = FALSE)
# activities <- activities_raw[[1]] %>%
#   clean_names()

# facilities addressed - we don't need these details
# facility_addresses_raw <- fromJSON("./data/raw/RIDBFullExport_V1_JSON/FacilityAddresses_API_v1.json",
#                       flatten = FALSE)
# facility_addresses <- facility_addresses_raw[[1]] %>%
#   clean_names()
# postal_code and address_state_code are reversed, and some states like UTAH are not always abbreviated

# nc_facility_addresses <- facility_addresses %>%
#   filter(postal_code == "NC",
#          facility_address_type != "Mailing")
# 
# nc_facility_addresses %>%
#   count(facility_id, sort = TRUE)

# facility_name_years_raw <- read_feather("./data/processed/park-years.feather") %>%
#   distinct(facility_id, site_type, start_year, .keep_all = TRUE) %>%
#   mutate_if(is.character, ~map_chr(.x, iconv, "UTF-8", "UTF-8", sub='')) %>% # just in case
#   left_join(.,
#             facilities,
#             by = "facility_id") %>%
#   mutate(use_type = str_to_lower(use_type),
#          facility_name = str_to_lower(facility_name))

```

```{r define-park-years}
# create df with list of all facilities that provide overnight camping and the first and last year reservations were offered in the dataset

path_csv <- "./data/raw/reservations/"

all_files_csv_hist <- fs::dir_ls(path = path_csv,
                        recurse = FALSE,
                        type = "file",
                        regexp = "[.]csv$"
)

get_park_years <- function(fname) {
  
  # test
  # fname <- "./data/raw/reservations/2017.csv"
  
  tbl_tmp <- read_csv(file = fname, 
                      col_types = cols(.default = "c"),
                      id = "path") %>%
    clean_names()
  
  tbl_tmp2 <- tbl_tmp
  
  if(any(str_detect(tbl_tmp2$path, "2019|2020"))) {
    tbl_tmp2 <- tbl_tmp2 %>%
      select(-starts_with(c("entityid", "equipment", "discount")))
    
    if(any(str_detect(tbl_tmp2$path, "2020"))) {
      tbl_tmp2 <- tbl_tmp2 %>% 
        select(-nights)
    }

    names(tbl_tmp2) <- c("path", "historical_reservation_id", "order_number", "agency", "org_id",
                         "code_hierarchy", "region_code", "region_description", "parent_location_id", "parent_location",
                         "legacy_facility_id", "park", "site_type", "use_type", "product_id",
                         "entity_type", "facility_id", "facility_zip", "facility_state",
                         "facility_longitude", "facility_latitude", "customer_zip", "customer_state", "customer_country",
                         "tax", "use_fee", "tran_fee", "attr_fee", "total_before_tax",
                         "total_paid", "start_date", "end_date", "order_date", "number_of_people") #, "nights") #TODO: are last two switched?
    
  }
  
  tbl_tmp2 <- tbl_tmp2 %>%
    select(path, agency, org_id, park:facility_latitude, ends_with("date")) %>%
    mutate(across(ends_with("date"), ~ as.Date(.x, origin = "1970-01-01"))) %>%
    mutate(across(ends_with(c("tude", "_people")), as.numeric)) %>%
    left_join(.,
              facilities %>% select(-facility_longitude, -facility_latitude),
              by = "facility_id") %>%
    mutate(start_year = year(start_date),
           order_year = year(order_date)) %>%
    
    # TODO: move this to specific get_years() function?
    distinct(facility_id, facility_name, site_type, start_year, order_year, .keep_all = TRUE) %>%
    mutate(facility_name = str_to_title(facility_name)) %>%
    select(-park, reservable, last_updated_date) %>%
    # drop items that don't include overnight reservations (or where not reservable, )
    filter(!is.na(facility_name), # drop some bad data
           !is.na(end_date), # drop things we know aren't really overnight camping (some tours are overnight, for example)
           use_type == "Overnight")
  
  tbl_tmp2
}

# all_files_selected <- all_files_csv_hist[str_detect(all_files_csv_hist, as.character(2019))]

# TODO: Run this again when I go to dinner
park_years_raw <- map_dfr(all_files_csv_hist, get_park_years)

park_years <- park_years_raw %>%
  mutate(
    site_type = str_to_lower(site_type),
    site_type_simple = case_when(
           str_detect(site_type, "tent")        ~ "tent",
           str_detect(site_type, "cabin|yurt")       ~ "cabin",
           str_detect(site_type, "group")       ~ "group",
           str_detect(site_type, "rm")          ~ "rv",
           str_detect(site_type, "equestrian")  ~ "equestrian",
           str_detect(site_type, "standard")    ~ "standard",
           str_detect(site_type, "shelter")     ~ "shelter",
           str_detect(site_type, "management")  ~ "management",
           str_detect(site_type, "walk to")     ~ "standard",
           str_detect(site_type, "hike in")     ~ "standard",
           str_detect(site_type, "hike in")     ~ "standard",
           str_detect(site_type, "lookout")     ~ "standard",
           str_detect(site_type, "boat in")     ~ "other",
           str_detect(site_type, "mooring")     ~ "other",
           str_detect(site_type, "anchorage")   ~ "other",
           str_detect(site_type, "yes|no")      ~ "other",
           str_detect(site_type, "picnic")      ~ "other",
           str_detect(site_type, "zone")        ~ "other",
           TRUE                                 ~ site_type
         )
  ) %>%
  distinct(facility_id, site_type_simple, start_year, order_year, .keep_all = TRUE)

write_feather(park_years, paste0("./data/processed/park-years.feather"))

# park_years %>%
#   count(site_type_simple, sort = TRUE)
```

```{r}
facilities %>%
  count(facility_type_description, sort = TRUE) %>%
  gt()

tbl_tmp2 %>%
  count(use_type, sort = TRUE) %>%
  gt()

tbl_tmp2 %>%
  count(facility_type_description, sort = TRUE) %>%
  gt()
```

